name: haoshengyi_jzzs_app
description: "好生意记账本 - 用说的方式记账，更轻松！"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  dio: ^5.4.0                # 网络请求
  provider: ^6.1.1           # 状态管理
  shared_preferences: ^2.0.0  # 本地存储
  speech_to_text: ^7.0.0     # 语音识别
  flutter_screenutil: ^5.9.0  # 屏幕适配
  flutter_easyloading: ^3.0.5 # 加载提示
  intl: ^0.19.0              # 国际化
  permission_handler: ^11.2.0 # 权限处理
  flutter_svg: ^2.0.9        # SVG图标
  cached_network_image: ^3.3.1 # 图片缓存
  fl_chart: ^0.70.0
  sqflite: ^2.3.0
  path_provider: ^2.1.2
  device_info_plus: ^9.1.1
  # 添加以下依赖
  # 必要的依赖
  flutter_sound: ^9.2.13
  crypto: ^3.0.3
  web_socket_channel: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/app_icon.png"
  
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/

